/**
 * @module CacheService
 * @description In-memory caching service for expensive AI computations in the Atmos API.
 *
 * Prevents redundant Gemini API calls by storing insights responses keyed by a
 * SHA-256 hash of the user's current carbon state (profile + ledger + offsetTarget).
 * If none of these change, reloading the dashboard returns the cached response instantly
 * rather than making a new (latency + cost) API call.
 *
 * Cache Efficiency Architecture:
 * - **State Hashing**: Uses SHA-256 to detect if the user's carbon ledger or offsetTarget
 *   has actually changed since the last insights generation.
 * - **TTL Eviction**: Entries older than {@link CACHE_TTL_MS} (10 minutes) are evicted
 *   on next read — ensuring users receive fresh AI analysis after significant time passes.
 * - **Explicit Invalidation**: Profile and goal mutations call `invalidateAll()` immediately
 *   to prevent stale coaching after ledger-state changes.
 */

import crypto from "crypto";
import { AtmosCoachResponse, UserProfile, ActivityLog } from "../types/index.js";
import { CACHE_TTL_MS } from "../constants/carbon.constants.js";

/** Shape of a single cache entry with a timestamp for TTL eviction. */
interface CacheEntry {
  /** The cached coach response data. */
  data: AtmosCoachResponse & { meta?: { source: string } };
  /** Unix timestamp (ms) when this entry was created. Used for TTL checks. */
  timestamp: number;
}

/**
 * In-memory caching service for AI-generated carbon coaching responses.
 *
 * Instantiated as a singleton (`cacheService`). All route handlers and controllers
 * interact with this singleton — no direct instantiation is required.
 */
class CacheService {
  /** Key-value store mapping SHA-256 state hashes to cached coach responses. */
  private cache: Record<string, CacheEntry> = {};

  /** Cache TTL in milliseconds sourced from {@link CACHE_TTL_MS}. */
  private readonly ttlMs = CACHE_TTL_MS;

  /**
   * Generates a deterministic SHA-256 hash representing the user's current carbon state.
   *
   * The hash is computed from three components combined with pipe separators:
   * 1. A compact representation of each emission entry (`id:co2eKg` pairs joined by commas).
   * 2. A JSON serialisation of the user's onboarding carbon profile.
   * 3. The current offsetTarget percentage as a string.
   *
   * If any of these values change, the hash changes, producing a cache miss and
   * triggering a fresh Gemini API call or local fallback generation.
   *
   * @param {UserProfile | null} profile - The user's onboarding carbon profile.
   * @param {ActivityLog[]} activities - The user's full carbon emission ledger.
   * @param {number} targetPercent - The user's current offsetTarget as a percentage.
   * @returns {string} A 64-character lowercase hex string of the SHA-256 state hash.
   */
  public generateStateHash(
    profile: UserProfile | null,
    activities: ActivityLog[],
    targetPercent: number
  ): string {
    const activitiesHash = activities.map((a) => `${a.id}:${a.emissions}`).join(",");
    const profileHash = profile ? JSON.stringify(profile) : "no-profile";
    const goalHash = String(targetPercent);
    const rawState = `${activitiesHash}|${profileHash}|${goalHash}`;

    return crypto.createHash("sha256").update(rawState).digest("hex");
  }

  /**
   * Retrieves a cached coach response if it exists and hasn't exceeded the TTL.
   *
   * Automatically evicts the entry from the cache if it has expired, freeing memory.
   *
   * @param {string} key - The SHA-256 state hash key generated by {@link generateStateHash}.
   * @returns {(AtmosCoachResponse & { meta?: { source: string } }) | null}
   *   The cached response, or `null` if the entry is missing or expired.
   */
  public get(key: string): (AtmosCoachResponse & { meta?: { source: string } }) | null {
    const entry = this.cache[key];
    if (!entry) return null;

    const now = Date.now();
    if (now - entry.timestamp > this.ttlMs) {
      delete this.cache[key];
      return null;
    }

    return entry.data;
  }

  /**
   * Stores a new coach response in the cache with the current timestamp.
   *
   * Overwrites any existing entry for the same key, effectively resetting its TTL.
   *
   * @param {string} key - The SHA-256 state hash key.
   * @param {AtmosCoachResponse & { meta?: { source: string } }} data - The response to cache.
   * @returns {void}
   */
  public set(key: string, data: AtmosCoachResponse & { meta?: { source: string } }): void {
    this.cache[key] = {
      data,
      timestamp: Date.now(),
    };
  }

  /**
   * Clears all entries from the cache immediately.
   *
   * Called by profile and goals controllers after mutations that alter the carbon
   * ledger state, ensuring the next insights request generates a fresh response.
   * Also used in test teardown to ensure a clean state between test cases.
   *
   * @returns {void}
   */
  public invalidateAll(): void {
    this.cache = {};
  }
}

export const cacheService = new CacheService();
